### ISSUE TITLE
Add Stripe.com as another payment method (instead or additionally to PayPal)

### ISSUE THREAD

**Issue by AR7RIX** [FlorianSW/server-donation-tool#43]
For example stripe.com

**Comment by FlorianSW** [comment]
Would you use stripe _instead_ of PayPal, or _additionally_ to it (basically presenting a choice to the user of what payment provider they want to choose)? 🤔

**Comment by AR7RIX** [comment]
> Would you use stripe _instead_ of PayPal, or _additionally_ to it (basically presenting a choice to the user of what payment provider they want to choose)? 🤔

dont know, but you can make it choosable when two options are enabled

**Comment by FlorianSW** [comment]
Tbh.: Most payment methods are redundant for the donator. There is not much benefit of showing both methods and then giving the donator the additional complexity of deciding what to choose. Additionally, it will be complicated to visually describe the user what these options even mean :/

**Comment by FlorianSW** [comment]
May I also ask, why you want/need another payment method in the first place? :)

**Comment by AR7RIX** [comment]
Some countries like Turkish for example cant use paypal i dont know if stripe.com supports it but maybe there is any alternatives.
And also i heard that paypal like to block paypal accounts. We will see in future :)

**Comment by lewk-io** [comment]
I've seen some websites use an Amazon payment gateway as well (ie https://real-debrid.com) not sure if that's something worth looking in to?

**Comment by FlorianSW** [comment]
I mean, once there is support for two payment providers, it shouldn't be too hard anymore to add more :D It's more of a problem to add one when there is only one right now :P (there is only 1 or 2 or many :D).

Right now, I've a somewhat _working_ but more than unstable version on a feature branch, where I work on from time to tim (should push the latest changes, I keep forgetting to commit the stuff I did on a day when it's, in the best case, ... unfinished).

What is working right now:
- configuring stripe as a second (or only) payment method
- Making a payment with stripe.com (the available payment methods are configured at stripe.com, the UI is fully responsive to these settings
- Redeeming a donation when the stripe payment succeeds

What is not done, yet (and where I need to think about):
- When a payment fails or is cancelled, the donator sees the "Redeem now" page. When the button is clicked, the donation is not redeemed, as the payment is not fulfilled, however, the experience here is somewhat bad
- I kind of dislike the "yet another payment provider UI framework/script inclusion". For starters: It makes the donation process a bit more complicated, and secondly: the benefit is small (embedded in the tools UI), and I like the stripe.com checkout page. It's clean and it will support stuff like G Pay and Apple Pay out-of-the-box, which the embedded UI does not right now.

What is your opinion on the last point? Would it be ok, if the donator is redirected to a payment screen built and maintained by stripe.com when it is selected as a payment method? Instead of having an embedded payment UI (like the one from PayPal right now)?
